In [5]:
import numpy as np
array=np.array([2,4,6,9,10])
print(array)


[ 2  4  6  9 10]


In [6]:
arr=array+2
print(arr)

[ 4  6  8 11 12]


In [7]:
arr1=array*3
print(arr1)

[ 6 12 18 27 30]


In [8]:
arr2=array/2
print(arr2)

[1.  2.  3.  4.5 5. ]


In [9]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
Reversed=arr[::-1]
print(Reversed)

[5 4 6 3 2 1]


In [18]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
unique_element,count=np.unique(x,return_counts=True)
m1=np.argmax(count)
m2=unique_element[m1]
print(m2)
indices = np.where(x== m2)[0]
print(indices)

1
[0 5 7 8 9]


In [19]:
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
unique_element,count=np.unique(y,return_counts=True)
m1=np.argmax(count)
m2=unique_element[m1]
print(m2)
indices = np.where(y== m2)[0]
print(indices)

1
[0 1 2]


In [22]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element=arr[0,1]
print(element)

20


In [23]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element=arr[2,0]
print(element)

70


In [46]:
import numpy as np
arshia=np.linspace(10,100,25)
print(arshia)

dim=arshia.ndim
print("Dimensions of the array:",dim)

shape=arshia.shape
print("Shape the array :",shape)

Total=arshia.size
print("Total number of elemets:",Total)

data_type=arshia.dtype
print("Data type:",data_type)

byte=arshia.nbytes
print("Total number of bytes:",byte)

transpose=np.reshape(arshia,(25,))
print("Transpose of arshia:",transpose)
t=arshia.T
print(t)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape the array : (25,)
Total number of elemets: 25
Data type: float64
Total number of bytes: 200
Transpose of arshia: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [45]:
import numpy as np
ucs420_arshia=np.array([[10, 20, 30,40],[ 50, 60, 70, 80],[ 90, 15, 20, 35]])
print(ucs420_arshia)

m1=np.mean(ucs420_arshia)
print("Mean: ",m1)

m2=np.median(ucs420_arshia)
print("Median:",m2)

m3=np.max(ucs420_arshia)
print("Max:",m3)

m4=np.min(ucs420_arshia)
print("Min:",m4)

m5=np.unique(ucs420_arshia)
print("Unique elements:",m5)

Reshaped_ucs420_arshia=np.reshape(ucs420_arshia,(4,3))
print("Reshaped Array:",Reshaped_ucs420_arshia)

Resized_ucs420_arshia=np.resize(ucs420_arshia,(2,3))
print("Resized Array:",Resized_ucs420_arshia)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean:  43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array: [[10 20 30]
 [40 50 60]]
